apiVersion: apps/v1
kind: Deployment
metadata:
  name: mojave-sequencer-deployment
  labels:
    app: mojave-sequencer
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mojave-sequencer
  template:
    metadata:
      labels:
        app: mojave-sequencer
    spec:
      serviceAccountName: mojave-sequencer-sa
      terminationGracePeriodSeconds: 30
      containers:
      - name: mojave-sequencer
        image: starkgiwook/mojave-sequencer:v0.1.1
        imagePullPolicy: Always
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: LEASE_NAME
            value: sequencer-leader
          - name: LEASE_TTL_SECONDS
            value: "15"
        args:
          - "init"
          - "--private_key"
          - "0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
          - "--network"
          - "/data/testnet-genesis.json"
          - "--http.port"
          - "18545"
          - "--authrpc.port"
          - "18551"
          - "--p2p.port"
          - "30305"
          - "--discovery.port"
          - "30305"
          - "--no-daemon"
        ports:
          - name: http
            containerPort: 18545
          - name: auth-rpc
            containerPort: 18551
          - name: p2p
            containerPort: 30305
            protocol: TCP
        livenessProbe:
          tcpSocket:
            port: 18545
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 18545
          initialDelaySeconds: 10
          periodSeconds: 5