apiVersion: v1
kind: PersistentVolume
metadata:
  name: sequencer-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: mojave-rwx
  hostPath:
    path: /data/mojave
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sequencer-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: mojave-rwx
  volumeName: sequencer-pv
