apiVersion: v1
kind: ServiceAccount
metadata:
  name: sequencer-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sequencer-lease-role
rules:
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sequencer-lease-rb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: sequencer-lease-role
subjects:
- kind: ServiceAccount
  name: sequencer-sa