apiVersion: v1
kind: Secret
metadata:
  name: sequencer-secrets
  namespace: 1sixtech
type: Opaque
data:
  private-key: MHhhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFh
