apiVersion: v1
kind: Service
metadata:
  name: mojave-sequencer
  namespace: 1sixtech
spec:
  clusterIP: None
  selector:
    app: mojave-sequencer
  ports:
    - name: http
      protocol: TCP
      port: 18545
      targetPort: 18545
    - name: p2p
      protocol: TCP
      port: 30303
      targetPort: 30303
    - name: p2p-udp
      protocol: UDP
      port: 30303
      targetPort: 30303
